# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devlog < Formula
  desc "Local-first engineer journal — git commits and PRs auto-imported"
  homepage "https://github.com/kacheo/devlog"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kacheo/devlog/releases/download/v0.2.0/devlog_0.2.0_darwin_amd64.tar.gz"
      sha256 "7b4a9bf57aec541220445b7a0aca6870bb5fd831b611ac72ebae918cab3f04dc"

      define_method(:install) do
        bin.install "devlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kacheo/devlog/releases/download/v0.2.0/devlog_0.2.0_darwin_arm64.tar.gz"
      sha256 "cbf77d738fdef5203af21c93c0602371948e2a39b8477570e7169e4476730710"

      define_method(:install) do
        bin.install "devlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kacheo/devlog/releases/download/v0.2.0/devlog_0.2.0_linux_amd64.tar.gz"
      sha256 "69d9abcbf7dde9482cea08445ebf0b0e665e4b8bea520bc8aa2f9aec1497c980"
      define_method(:install) do
        bin.install "devlog"
      end
    end
  end

  test do
    system "#{bin}/devlog", "--version"
  end
end
